spring:
  profiles:
    active: test
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ydnhcfwmzkfbdg
    password: c3c96ff80af2201effa2e6d14192110a3deb9e8033d42959fb6041489dde3cf1
    url: jdbc:postgresql://ec2-54-224-64-114.compute-1.amazonaws.com:5432/d79vrmch5eamf9
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
