spring:
  profiles: test
  security:
    user:
      name: admin
      password: admin
  datasource:
    driver-class-name: org.postgresql.Driver
    username: nhtgtadzolvmwx
    password: 1be1c3ef65ca4216675e60db65d8ab0361b46e55e014f76d1b3934ec73c23667
    url: jdbc:postgresql://ec2-3-225-41-234.compute-1.amazonaws.com:5432/db418n8fgfk7de
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
